<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:structure.allure.qatools.yandex.ru" failed="1" passed="1" skipped="1" broken="1" tests="4" start="1381237019825" stop="1381237020038" duration="213" attachments-count="0" status="failed">
    <uid>c51469d88be9f49cf313cabc267314e84dd67d1824608e01a03a8cc0bfe25a88</uid>
    <name>my.company.TestWithoutSteps</name>
    <title>Test without steps</title>
    <test-cases start="1381237019853" stop="1381237019877" duration="24" steps-count="0" attachments-count="0" status="skipped" severity="normal">
        <uid>828c44d4923154aba031c365aafa8d95e28a6cca7312615323a5d72fd269ce2c</uid>
        <parent-uid>c51469d88be9f49cf313cabc267314e84dd67d1824608e01a03a8cc0bfe25a88</parent-uid>
        <name>skippedTestWithoutSteps</name>
        <title>Skipped test without steps</title>
        <classname>my.company.TestWithoutSteps</classname>
        <story-info title="My allure story" uid="288374d4-655f-4534-a2b4-a4ee0c51169c" feature-uid="fc68e2c7-d525-4b79-9fc0-54012c511100"/>
        <feature-info title="My allure feature" uid="fc68e2c7-d525-4b79-9fc0-54012c511100"/>
    </test-cases>
    <test-cases start="1381237020005" stop="1381237020012" duration="7" steps-count="0" attachments-count="0" status="passed" severity="normal">
        <uid>64a45ea3c5ffe2082d9590c59b30aedc0f3432744e4371b527f600dccf4d84ec</uid>
        <parent-uid>c51469d88be9f49cf313cabc267314e84dd67d1824608e01a03a8cc0bfe25a88</parent-uid>
        <name>passedTestWithoutSteps</name>
        <title>Passed test without steps</title>
        <classname>my.company.TestWithoutSteps</classname>
    </test-cases>
    <test-cases start="1381237020014" stop="1381237020021" duration="7" steps-count="0" attachments-count="0" status="failed" severity="normal">
        <uid>9a86126cdcb922afbf4f950b533f49045b595c826c0b44938a3421ae58fce017</uid>
        <parent-uid>c51469d88be9f49cf313cabc267314e84dd67d1824608e01a03a8cc0bfe25a88</parent-uid>
        <name>failedTestWithoutSteps</name>
        <title>Failed test without steps</title>
        <classname>my.company.TestWithoutSteps</classname>
        <failure>
            <message>5 is not 2 + 2
Expected: is &lt;4&gt;
     but: was &lt;5&gt;</message>
            <stack-trace>java.lang.AssertionError: 5 is not 2 + 2
Expected: is &lt;4&gt;
     but: was &lt;5&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at my.company.TestWithoutSteps.failedTestWithoutSteps(TestWithoutSteps.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</stack-trace>
        </failure>
    </test-cases>
    <test-cases start="1381237020027" stop="1381237020033" duration="6" steps-count="0" attachments-count="0" status="broken" severity="normal">
        <uid>3951495b255012b21412944210fbab3da4718b82c9c5a496234ccf0ae7eb3fb1</uid>
        <parent-uid>c51469d88be9f49cf313cabc267314e84dd67d1824608e01a03a8cc0bfe25a88</parent-uid>
        <name>brokenTestWithoutSteps</name>
        <title>Broken test without steps</title>
        <classname>my.company.TestWithoutSteps</classname>
        <failure>
            <message>1</message>
            <stack-trace>java.lang.ArrayIndexOutOfBoundsException: 1
	at my.company.TestWithoutSteps.brokenTestWithoutSteps(TestWithoutSteps.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
</stack-trace>
        </failure>
    </test-cases>
</ns2:test-suite>
